# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  # 基础信息
  metrics-base:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          template: classic
          filename: metrics.base.svg
          base: header, metadata
          config_timezone: Asia/Shanghai
  
  # 日历插件
  metrics-calendar:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          template: classic
          filename: metrics.calendar.svg
          base: ""
          config_timezone: Asia/Shanghai
          plugin_calendar: yes
          plugin_calendar_limit: 2
  
  # 等距日历插件
  metrics-isocalendar:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          template: classic
          filename: metrics.isocalendar.svg
          base: ""
          config_timezone: Asia/Shanghai
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
  
  # 关注仓库插件
  metrics-followup:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          template: classic
          filename: metrics.followup.svg
          base: ""
          config_timezone: Asia/Shanghai
          plugin_followup: yes
          plugin_followup_archived: yes
          plugin_followup_sections: repositories
  
  # 自我介绍插件
  metrics-introduction:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          template: classic
          filename: metrics.introduction.svg
          base: ""
          config_timezone: Asia/Shanghai
          plugin_introduction: yes
          plugin_introduction_title: yes
  
  # 反应插件
  metrics-reactions:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          template: classic
          filename: metrics.reactions.svg
          base: ""
          config_timezone: Asia/Shanghai
          plugin_reactions: yes
          plugin_reactions_display: absolute
          plugin_reactions_limit: 200
          plugin_reactions_limit_discussions: 100
          plugin_reactions_limit_discussions_comments: 100
          plugin_reactions_limit_issues: 100
  
  # 收藏仓库插件
  metrics-stars:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          template: classic
          filename: metrics.stars.svg
          base: ""
          config_timezone: Asia/Shanghai
          plugin_stars: yes
          plugin_stars_limit: 4
